/* prettier-ignore-start */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as AddEntryImport } from './routes/add-entry'
import { Route as indexImport } from './routes/index'
import { Route as EntryUserIdEntryIdImport } from './routes/entry/$userId/$entryId'

// Create/Update Routes

const PrivacyRoute = PrivacyImport.update({
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const AddEntryRoute = AddEntryImport.update({
  path: '/add-entry',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = indexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EntryUserIdEntryIdRoute = EntryUserIdEntryIdImport.update({
  path: '/entry/$userId/$entryId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRoute
      parentRoute: typeof rootRoute
    }
    '/add-entry': {
      id: '/add-entry'
      path: '/add-entry'
      fullPath: '/add-entry'
      preLoaderRoute: typeof AddEntryRoute
      parentRoute: typeof rootRoute
    }
    '/entry/$userId/$entryId': {
      id: '/entry/$userId/$entryId'
      path: '/entry/$userId/$entryId'
      fullPath: '/entry/$userId/$entryId'
      preLoaderRoute: typeof EntryUserIdEntryIdRoute
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRoute
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AddEntryRoute,
  EntryUserIdEntryIdRoute,
  PrivacyRoute,
})

/* prettier-ignore-end */
