// scripts/update-env.js
import { execSync } from "child_process";
import fs from "fs";
import path from "path";

// Always write to .env.local for dev
const envPath = path.resolve(process.cwd(), ".env.local");

// Run dfx canister id to get the current IDs
const backendId = execSync("dfx canister id journal_backend --network local").toString().trim();
const frontendId = execSync("dfx canister id journal_frontend --network local").toString().trim();

// Define clean VITE_* vars
const envContent = `# Auto-generated by update-env.js
VITE_DFX_VERSION=0.29.1
VITE_DFX_NETWORK=local
VITE_IC_HOST=http://127.0.0.1:4943
VITE_II_URL=https://identity.ic0.app/#authorize

# Local Canister IDs
VITE_CANISTER_ID_JOURNAL_BACKEND=${backendId}
VITE_CANISTER_ID_JOURNAL_FRONTEND=${frontendId}
`;

fs.writeFileSync(envPath, envContent);

console.log("✅ .env.local updated with VITE_ variables for local development");
